# Generated by Django 3.2.18 on 2023-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('golden', 'Golden')], default='bronze', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
