# Generated by Django 3.2.18 on 2023-05-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230516_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scope',
            field=models.CharField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Golden')], default=1, max_length=50),
        ),
    ]
