# Generated by Django 3.2.18 on 2023-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('user', '0006_auto_20230428_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
